"""
utils.py
--------
Shared utilities: image I/O, bounding box rendering, and
detection visualisation helpers for the PowerLine Vision project.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pathlib import Path
from typing import Optional


# ── Colours ───────────────────────────────────────────────────────────────────

CLASS_COLOURS = {
    0: (0, 200, 255),    # power_line — cyan (BGR)
    1: (50, 255, 50),    # tower      — green (BGR)
}

CLASS_NAMES = {
    0: "power_line",
    1: "tower",
}


# ── Image I/O ─────────────────────────────────────────────────────────────────

def load_image(image_path: str | Path) -> np.ndarray:
    """
    Load an image from disk as a BGR numpy array.
    Raises FileNotFoundError if the path does not exist.
    """
    path = Path(image_path)
    if not path.exists():
        raise FileNotFoundError(f"Image not found: {path}")
    image = cv2.imread(str(path))
    if image is None:
        raise ValueError(f"OpenCV failed to load image: {path}")
    return image


def save_image(image: np.ndarray, output_path: str | Path) -> None:
    """Save a BGR numpy array to disk, creating parent directories as needed."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(output_path), image)


# ── Bounding Box Rendering ───────────────────────────────────────────────────

def draw_detections(
    image: np.ndarray,
    boxes: list[list[float]],
    scores: list[float],
    class_ids: list[int],
    conf_threshold: float = 0.25,
    line_thickness: int = 2,
    font_scale: float = 0.55,
) -> np.ndarray:
    """
    Draw detection bounding boxes and labels on an image.

    Args:
        image:          BGR image to draw on (modified in-place copy)
        boxes:          List of [x1, y1, x2, y2] pixel coordinates
        scores:         Confidence scores per detection
        class_ids:      Class index per detection
        conf_threshold: Minimum confidence to render a detection
        line_thickness: Rectangle border thickness in pixels
        font_scale:     Text font scale

    Returns:
        Annotated BGR image
    """
    annotated = image.copy()
    h, w = annotated.shape[:2]

    for box, score, cls_id in zip(boxes, scores, class_ids):
        if score < conf_threshold:
            continue

        colour = CLASS_COLOURS.get(cls_id, (200, 200, 200))
        label = f"{CLASS_NAMES.get(cls_id, str(cls_id))} {score:.2f}"

        x1, y1, x2, y2 = [int(v) for v in box]
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w - 1, x2), min(h - 1, y2)

        # Draw box
        cv2.rectangle(annotated, (x1, y1), (x2, y2), colour, line_thickness)

        # Draw label background
        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, font_scale, 1)
        label_y = max(y1 - 4, text_h + 4)
        cv2.rectangle(
            annotated, (x1, label_y - text_h - 4), (x1 + text_w, label_y), colour, -1
        )
        cv2.putText(
            annotated, label, (x1, label_y - 2),
            cv2.FONT_HERSHEY_SIMPLEX, font_scale, (0, 0, 0), 1, cv2.LINE_AA
        )

    return annotated


# ── Matplotlib Visualisation ─────────────────────────────────────────────────

def plot_image_grid(
    images: list[np.ndarray],
    titles: Optional[list[str]] = None,
    cols: int = 3,
    figsize: tuple = (15, 10),
    output_path: Optional[str | Path] = None,
) -> None:
    """
    Display or save a grid of BGR images using Matplotlib.

    Args:
        images:      List of BGR numpy arrays
        titles:      Optional list of subplot titles
        cols:        Number of columns in the grid
        figsize:     Figure size in inches
        output_path: If provided, save to disk instead of displaying
    """
    n = len(images)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    axes = axes.flatten() if n > 1 else [axes]

    for i, ax in enumerate(axes):
        if i < n:
            rgb = cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB)
            ax.imshow(rgb)
            if titles and i < len(titles):
                ax.set_title(titles[i], fontsize=10)
            ax.axis("off")
        else:
            ax.axis("off")

    plt.tight_layout()
    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(str(output_path), dpi=150, bbox_inches="tight")
        print(f"Grid saved: {output_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_training_curves(results_csv: str | Path, output_dir: str | Path) -> None:
    """
    Parse Ultralytics training results CSV and plot loss and mAP curves.

    Args:
        results_csv: Path to results.csv generated by Ultralytics during training
        output_dir:  Directory to save the plots
    """
    import pandas as pd

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(results_csv)
    df.columns = [c.strip() for c in df.columns]

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    # Box loss
    if "train/box_loss" in df.columns:
        axes[0].plot(df["epoch"], df["train/box_loss"], label="Train", linewidth=2)
        if "val/box_loss" in df.columns:
            axes[0].plot(df["epoch"], df["val/box_loss"], label="Val", linewidth=2, linestyle="--")
        axes[0].set_title("Box Loss")
        axes[0].set_xlabel("Epoch")
        axes[0].legend()
        axes[0].grid(alpha=0.3)

    # mAP@0.5
    if "metrics/mAP50(B)" in df.columns:
        axes[1].plot(df["epoch"], df["metrics/mAP50(B)"], color="green", linewidth=2)
        axes[1].set_title("mAP@0.5")
        axes[1].set_xlabel("Epoch")
        axes[1].set_ylim(0, 1)
        axes[1].grid(alpha=0.3)

    # mAP@0.5:0.95
    if "metrics/mAP50-95(B)" in df.columns:
        axes[2].plot(df["epoch"], df["metrics/mAP50-95(B)"], color="darkorange", linewidth=2)
        axes[2].set_title("mAP@0.5:0.95")
        axes[2].set_xlabel("Epoch")
        axes[2].set_ylim(0, 1)
        axes[2].grid(alpha=0.3)

    plt.suptitle("PowerLine Vision — Training Curves", fontsize=13, fontweight="bold")
    plt.tight_layout()
    out_path = output_dir / "training_curves.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Training curves saved: {out_path}")
